package com.polytech.multimedia_library.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;

/**
 * @author Bruno Buiret <bruno.buiret@etu.univ-lyon1.fr>
 */
public class DatabaseConnection
{
    /**
     * The unique instance of this class.
     */
    protected static DatabaseConnection instance = null;
    
    /**
     * The actual connection to the database.
     */
    protected Connection connection = null;
    
    /**
     * Prevents this class from being instantiated outside of this file.
     */
    protected DatabaseConnection()
    {
        try
        {
            Context globalContext = new InitialContext();
            Context environmentContext = (Context) globalContext.lookup("java:comp/env");
            DataSource dataSource = (DataSource) environmentContext.lookup("jdbc/DSOeuvre");
            
            this.connection = dataSource.getConnection();
        }
        catch(SQLException | NamingException e)
        {
            // @todo Error handling.
            e.printStackTrace();
        }
    }
    
    /**
     * Gets a unique instance of this class.
     * 
     * @return The unique instance of this class.
     */
    public static DatabaseConnection getInstance()
    {
        if(null == DatabaseConnection.instance)
        {
            DatabaseConnection.instance = new DatabaseConnection();
        }
        
        return DatabaseConnection.instance;
    }
    
    /**
     * 
     * @param query
     * @return 
     */
    public PreparedStatement prepare(String query)
    {
        try
        {
            return this.connection.prepareStatement(query);
        }
        catch(SQLException e)
        {
            // @todo Error handling.
        }
        
        return null;
    }
    
    /**
     * 
     * @param query
     * @param autoGeneratedKeys
     * @return 
     */
    public PreparedStatement prepare(String query, int autoGeneratedKeys)
    {
        try
        {
            return this.connection.prepareStatement(query, autoGeneratedKeys);
        }
        catch(SQLException e)
        {
            // @todo Error handling.
        }
        
        return null;
    }
    
    /**
     * Begins a transaction.
     * 
     * @throws SQLException 
     */
    public void beginTransaction()
    throws SQLException
    {
        this.connection.setAutoCommit(false);
    }
    
    /**
     * Ends a transaction by committing it.
     * 
     * @throws SQLException 
     */
    public void endTransaction()
    throws SQLException
    {
        this.connection.commit();
        this.connection.setAutoCommit(true);
    }
    
    /**
     * Ends a transaction by roll backing.
     * 
     * @throws SQLException 
     */
    public void cancelTransaction()
    throws SQLException
    {
        this.connection.rollback();
        this.connection.setAutoCommit(true);
    }
}
